### ISSUE TITLE
Fix email platform

### ISSUE THREAD

**Issue by Eeap** [sunhofficial/sunhofficial#4]
@sunhofficial 
How about changing the email platform from naver to google?
I think it is better :)

`[![Gmail Badge](https://img.shields.io/badge/Gmail-d14836?style=flat-square&logo=Gmail&logoColor=white&link=mailto:yourID@gmail.com)](mailto:yourID@gmail.com)`

**Comment by sunhofficial** [comment]
Thanks for your advice!🤔But Can I ask the reason?

**Comment by Eeap** [comment]
> 

Because It could be that some developers don't know what naver is

**Comment by sunhofficial** [comment]
oh I see.. I agree with you! okay I'll change the email ASAP

**Comment by Eeap** [comment]
LGTM 👍
